# -*- coding: utf-8 -*-
"""AtividadeSupervisionadaIII.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Rx5U1Rixhsna7YuND1W0BrpxzUF91Lq
"""

import numpy as np

# Função de ativação degrau
def stepFunction(soma):
    return 1 if soma >= 1 else 0

# Função para treinar a Perceptron
def treinar_perceptron(entradas, saidas, pesos, taxa_aprendizado, epocas):
    print("\n### Iniciando o treinamento da Perceptron ###\n")
    for epoca in range(epocas):
        print(f"Época {epoca + 1}:")
        for i in range(len(entradas)):
            x = entradas[i]
            y_real = saidas[i]
            y_previsto = stepFunction(np.dot(x, pesos))#Calcula a saída prevista.
            erro = y_real - y_previsto#Se os valores forem diferentes ajusta o peso.

            # Explicação do processo de aprendizagem da IA/Perceptron
            print(f"  Entrada: {x}, Saída Esperada: {y_real}")
            print(f"  Soma (Produto Escalar): {np.dot(x, pesos)}")
            print(f"  Saída Prevista: {y_previsto}")
            print(f"  Erro: {erro}")

            # Atualizando os pesos caso tenha algum erro
            if erro != 0:
                print(f"  Atualizando pesos: {pesos} + ({taxa_aprendizado} * {erro} * {x})") # Valor de "erro" é a diferença entre a saída prevista e a esperada
                pesos += taxa_aprendizado * erro * x
                print(f"  Novos pesos: {pesos}\n")
            else:
                print(f"  Nenhuma atualização necessária.\n")

    print(f"Treinamento finalizado após {epocas} épocas.")  # Exibir quantidade de épocas
    print(f"Pesos finais: {pesos}\n")  # Exibir pesos finais
    return pesos

# Entrada de pesos do teclado
pesos = np.array(list(map(float, input("Digite os pesos iniciais (separados por espaço, ex: 0.0 0.0): ").split())))

# Garantindo que os pesos tenham exatamente 2 valores
if len(pesos) != 2:
    raise ValueError("Erro: Você deve inserir exatamente 2 pesos.")

# Entrada de sinais de entrada e as classes esperadas
entradas = []
saidas = []
print("Digite as entradas e as classes esperadas (formato: x1 x2 Classe):")
for _ in range(4):
    linha = list(map(int, input().split()))
    if len(linha) != 3:
        raise ValueError("Erro: Cada linha deve conter exatamente 3 valores (x1 x2 Classe).")
    entradas.append(linha[:2])  # x1 e x2
    saidas.append(linha[2])  # Classe esperada

# Convertendo para arrays numpy
entradas = np.array(entradas)
saidas = np.array(saidas)

# Treinamento da Perceptron
taxa_aprendizado = 0.1
epocas = 10
pesos = treinar_perceptron(entradas, saidas, pesos, taxa_aprendizado, epocas)

# Testando a Perceptron treinada
print("\n### Resultados após o treinamento ###")
print("x1 | x2 | Soma(Produto Escalar)  | Classe Prevista")  # Ajuste no cabeçalho pra ficar mais facil do usuário visualizar
print("---------------------------------")
for i in range(len(entradas)):
    soma = np.dot(entradas[i], pesos)
    y_previsto = stepFunction(soma)
    print(f"{entradas[i][0]}  |  {entradas[i][1]} | {soma:.2f} |    {y_previsto}")